<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE object
[
   <!ELEMENT object (#PCDATA|object)*>
   <!ATTLIST object name      CDATA #REQUIRED>
   <!ATTLIST object class     CDATA #REQUIRED>
   <!ATTLIST object primitive CDATA "no">
   <!ATTLIST object array     CDATA "no">   <!-- the dimensions of the array; no=0, yes=1 -->
   <!ATTLIST object null      CDATA "no">
   <!ATTLIST object version   CDATA "3.8.6">
]
>

<object class="weka.classifiers.trees.RandomForest" name="__root__" version="3.8.6">
   <object class="boolean" name="debug" primitive="yes">false</object>
   <object array="yes" class="java.lang.String" name="options">
      <object class="java.lang.String" name="0">-P</object>
      <object class="java.lang.String" name="1">100</object>
      <object class="java.lang.String" name="2">-I</object>
      <object class="java.lang.String" name="3">100</object>
      <object class="java.lang.String" name="4">-num-slots</object>
      <object class="java.lang.String" name="5">1</object>
      <object class="java.lang.String" name="6">-K</object>
      <object class="java.lang.String" name="7">0</object>
      <object class="java.lang.String" name="8">-M</object>
      <object class="java.lang.String" name="9">1.0</object>
      <object class="java.lang.String" name="10">-V</object>
      <object class="java.lang.String" name="11">0.001</object>
      <object class="java.lang.String" name="12">-S</object>
      <object class="java.lang.String" name="13">1</object>
   </object>
</object>
